# Generated by Django 4.2.7 on 2023-11-08 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chathistory',
            name='chat_type',
        ),
        migrations.AddField(
            model_name='chathistory',
            name='room_name',
            field=models.CharField(max_length=99, null=True),
        ),
    ]
